#!/bin/bash

DOCKER_USER=mulin
WEBHOOK_VERSION=v4.1
dep ensure -v
CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o lxcfs-admission-webhook
docker build --no-cache -t csighub.tencentyun.com/${DOCKER_USER}/lxcfs-admission-webhook:${WEBHOOK_VERSION} .
#docker build --no-cache -t ccr.ccs.tencentyun.com/mulin-lxcfs/lxcfs-admission-webhook:${WEBHOOK_VERSION} .
rm -rf lxcfs-admission-webhook

docker push csighub.tencentyun.com/${DOCKER_USER}/lxcfs-admission-webhook:${WEBHOOK_VERSION}
#docker push ccr.ccs.tencentyun.com/mulin-lxcfs/lxcfs-admission-webhook:${WEBHOOK_VERSION}

