#!/bin/bash

DOCKER_USER=mulin

dep ensure -v
CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o lxcfs-admission-webhook
docker build --no-cache -t csighub.tencentyun.com/${DOCKER_USER}/lxcfs-admission-webhook:v1 .
rm -rf lxcfs-admission-webhook

docker push csighub.tencentyun.com/${DOCKER_USER}/lxcfs-admission-webhook:v1
