apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lxcfs
  namespace: lxcfs
  labels:
    app: lxcfs
spec:
  selector:
    matchLabels:
      app: lxcfs
  template:
    metadata:
      labels:
        app: lxcfs
    spec:
      hostPID: true
      hostNetwork: true
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: lxcfs
        image: ccr.ccs.tencentyun.com/mulin/lxcfs:4.0.7
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
        - name: lxcfs
          mountPath: /var/lib/lxc/lxcfs
          mountPropagation: Bidirectional
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - 9.219.9.91
                      - 9.219.9.92
                      - 9.219.9.93
                      - 9.219.9.95
      volumes:
      - name: lxcfs
        hostPath:
          path: /var/lib/lxc/lxcfs
          type: DirectoryOrCreate
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10000
    type: RollingUpdate

